version: '3.8'

services:
  frontend:
    # build:
    #   context: .
    image: ghcr.io/nghiemquochung/dinh_gia_bds:latest
    container_name: check-bds-frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge